on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          outputs: build
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: Dockerfile.build
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            BUILD_VERSION=${{ steps.prepare.outputs.tag_name }} \
            FLUENT_VERSION=1.9.2

      - name: Build project
        run: |
          tar czf build/linux_amd64.tgz -C build/linux_amd64 flb-in_mem2.so
          tar czf build/linux_arm64.tgz -C build/linux_arm64 flb-in_mem2.so
          tar czf build/linux_arm_v7.tgz -C build/linux_arm_v7 flb-in_mem2.so

      - name: Create Release
        id: create_release
        uses: fopina/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          allow_update: true

      - name: Upload Release Asset
        id: upload-release-asset-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/linux_amd64.tgz
          asset_name: flb-in_mem2_linux_amd64.tgz
          asset_content_type: application/gzip
      - name: Upload Release Asset
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/linux_arm64.tgz
          asset_name: flb-in_mem2_linux_arm64.tgz
          asset_content_type: application/gzip
      - name: Upload Release Asset
        id: upload-release-asset-3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/linux_arm_v7.tgz
          asset_name: flb-in_mem2_linux_arm_v7.tgz
          asset_content_type: application/gzip
